/*
 * Copyright (C) 2025 LooKeR & Contributors
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.looker.kenko.ui.theme.colorSchemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.looker.kenko.R

// Catppuccin — Latte (Light) & Mocha (Dark)

private val primaryLight = Color(0xFF1E66F5)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFD6E4FF)
private val onPrimaryContainerLight = Color(0xFF001B5E)
private val secondaryLight = Color(0xFFEA76CB)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFD7F2)
private val onSecondaryContainerLight = Color(0xFF5C1148)
private val tertiaryLight = Color(0xFF179299)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC4FAF5)
private val onTertiaryContainerLight = Color(0xFF003739)
private val errorLight = Color(0xFFD20F39)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD5)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFEFF1F5)
private val onBackgroundLight = Color(0xFF4C4F69)
private val surfaceLight = Color(0xFFEFF1F5)
private val onSurfaceLight = Color(0xFF4C4F69)
private val surfaceVariantLight = Color(0xFFCCD0DA)
private val onSurfaceVariantLight = Color(0xFF6C6F85)
private val outlineLight = Color(0xFF9CA0B0)
private val outlineVariantLight = Color(0xFFBCC0CC)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF5C5F77)
private val inverseOnSurfaceLight = Color(0xFFF4F5F9)
private val inversePrimaryLight = Color(0xFF7287FD)
private val surfaceDimLight = Color(0xFFDCE0E8)
private val surfaceBrightLight = Color(0xFFFAFBFD)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF4F6FA)
private val surfaceContainerLight = Color(0xFFEFF1F5)
private val surfaceContainerHighLight = Color(0xFFE6E9EF)
private val surfaceContainerHighestLight = Color(0xFFE0E2EA)

private val primaryLightMediumContrast = Color(0xFF0043C0)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF4A7FF7)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFFC8189D)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFFEE85D5)
private val onSecondaryContainerLightMediumContrast = Color(0xFF000000)
private val tertiaryLightMediumContrast = Color(0xFF00737A)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF4DBABC)
private val onTertiaryContainerLightMediumContrast = Color(0xFF000000)
private val errorLightMediumContrast = Color(0xFFAD0026)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFE84C51)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFEFF1F5)
private val onBackgroundLightMediumContrast = Color(0xFF4C4F69)
private val surfaceLightMediumContrast = Color(0xFFEFF1F5)
private val onSurfaceLightMediumContrast = Color(0xFF4C4F69)
private val surfaceVariantLightMediumContrast = Color(0xFFCCD0DA)
private val onSurfaceVariantLightMediumContrast = Color(0xFF565A70)
private val outlineLightMediumContrast = Color(0xFF888CA2)
private val outlineVariantLightMediumContrast = Color(0xFFA4A8BD)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF5C5F77)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F5F9)
private val inversePrimaryLightMediumContrast = Color(0xFF7287FD)
private val surfaceDimLightMediumContrast = Color(0xFFDCE0E8)
private val surfaceBrightLightMediumContrast = Color(0xFFFAFBFD)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF4F6FA)
private val surfaceContainerLightMediumContrast = Color(0xFFEFF1F5)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE6E9EF)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE0E2EA)

private val primaryLightHighContrast = Color(0xFF002174)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF0043C0)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF4A0035)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFFC8189D)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF002021)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF00737A)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFFAD0026)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFEFF1F5)
private val onBackgroundLightHighContrast = Color(0xFF4C4F69)
private val surfaceLightHighContrast = Color(0xFFEFF1F5)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFCCD0DA)
private val onSurfaceVariantLightHighContrast = Color(0xFF2A2D40)
private val outlineLightHighContrast = Color(0xFF565A70)
private val outlineVariantLightHighContrast = Color(0xFF565A70)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF5C5F77)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFBAC8FF)
private val surfaceDimLightHighContrast = Color(0xFFDCE0E8)
private val surfaceBrightLightHighContrast = Color(0xFFFAFBFD)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF4F6FA)
private val surfaceContainerLightHighContrast = Color(0xFFEFF1F5)
private val surfaceContainerHighLightHighContrast = Color(0xFFE6E9EF)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE0E2EA)

private val primaryDark = Color(0xFF89B4FA)
private val onPrimaryDark = Color(0xFF002A8A)
private val primaryContainerDark = Color(0xFF1E4890)
private val onPrimaryContainerDark = Color(0xFFD6E4FF)
private val secondaryDark = Color(0xFFF5C2E7)
private val onSecondaryDark = Color(0xFF5C1148)
private val secondaryContainerDark = Color(0xFF7A3060)
private val onSecondaryContainerDark = Color(0xFFFFD7F2)
private val tertiaryDark = Color(0xFF94E2D5)
private val onTertiaryDark = Color(0xFF003739)
private val tertiaryContainerDark = Color(0xFF005F5F)
private val onTertiaryContainerDark = Color(0xFFC4FAF5)
private val errorDark = Color(0xFFF38BA8)
private val onErrorDark = Color(0xFF5C0010)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD5)
private val backgroundDark = Color(0xFF1E1E2E)
private val onBackgroundDark = Color(0xFFCDD6F4)
private val surfaceDark = Color(0xFF1E1E2E)
private val onSurfaceDark = Color(0xFFCDD6F4)
private val surfaceVariantDark = Color(0xFF313244)
private val onSurfaceVariantDark = Color(0xFFA6ADC8)
private val outlineDark = Color(0xFF6C7086)
private val outlineVariantDark = Color(0xFF45475A)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE4E5F0)
private val inverseOnSurfaceDark = Color(0xFF313244)
private val inversePrimaryDark = Color(0xFF1E66F5)
private val surfaceDimDark = Color(0xFF11111B)
private val surfaceBrightDark = Color(0xFF45475A)
private val surfaceContainerLowestDark = Color(0xFF0B0B14)
private val surfaceContainerLowDark = Color(0xFF181825)
private val surfaceContainerDark = Color(0xFF1E1E2E)
private val surfaceContainerHighDark = Color(0xFF313244)
private val surfaceContainerHighestDark = Color(0xFF3D3D52)

private val primaryDarkMediumContrast = Color(0xFFAFCAFF)
private val onPrimaryDarkMediumContrast = Color(0xFF001240)
private val primaryContainerDarkMediumContrast = Color(0xFF528DED)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFF8CDEC)
private val onSecondaryDarkMediumContrast = Color(0xFF330023)
private val secondaryContainerDarkMediumContrast = Color(0xFFBA85CE)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFADF5EB)
private val onTertiaryDarkMediumContrast = Color(0xFF001F20)
private val tertiaryContainerDarkMediumContrast = Color(0xFF5CCCC0)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFB3B0)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF1E1E2E)
private val onBackgroundDarkMediumContrast = Color(0xFFCDD6F4)
private val surfaceDarkMediumContrast = Color(0xFF1E1E2E)
private val onSurfaceDarkMediumContrast = Color(0xFFF8F9FF)
private val surfaceVariantDarkMediumContrast = Color(0xFF313244)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFC7CDE5)
private val outlineDarkMediumContrast = Color(0xFF9DA3BD)
private val outlineVariantDarkMediumContrast = Color(0xFF7D839C)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE4E5F0)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF313244)
private val inversePrimaryDarkMediumContrast = Color(0xFF1E4890)
private val surfaceDimDarkMediumContrast = Color(0xFF11111B)
private val surfaceBrightDarkMediumContrast = Color(0xFF45475A)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0B0B14)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF181825)
private val surfaceContainerDarkMediumContrast = Color(0xFF1E1E2E)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF313244)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3D52)

private val primaryDarkHighContrast = Color(0xFFF8F9FF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFAFCAFF)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFFF9FB)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFF8CDEC)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFF1FFFC)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFADF5EB)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFB3B0)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF1E1E2E)
private val onBackgroundDarkHighContrast = Color(0xFFCDD6F4)
private val surfaceDarkHighContrast = Color(0xFF1E1E2E)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF313244)
private val onSurfaceVariantDarkHighContrast = Color(0xFFF8F9FF)
private val outlineDarkHighContrast = Color(0xFFC7CDE5)
private val outlineVariantDarkHighContrast = Color(0xFFC7CDE5)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE4E5F0)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF00215A)
private val surfaceDimDarkHighContrast = Color(0xFF11111B)
private val surfaceBrightDarkHighContrast = Color(0xFF45475A)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0B0B14)
private val surfaceContainerLowDarkHighContrast = Color(0xFF181825)
private val surfaceContainerDarkHighContrast = Color(0xFF1E1E2E)
private val surfaceContainerHighDarkHighContrast = Color(0xFF313244)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF3D3D52)

private val catppuccinLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val catppuccinDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val catppuccinMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val catppuccinHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val catppuccinMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val catppuccinHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val catppuccinColorSchemes = ColorSchemes(
    light = catppuccinLightScheme,
    dark = catppuccinDarkScheme,
    mediumContrastLight = catppuccinMediumContrastLightColorScheme,
    mediumContrastDark = catppuccinMediumContrastDarkColorScheme,
    highContrastLight = catppuccinHighContrastLightColorScheme,
    highContrastDark = catppuccinHighContrastDarkColorScheme,
    nameRes = R.string.label_color_scheme_catppuccin,
)
