/*
 * Copyright (C) 2025 LooKeR & Contributors
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.looker.kenko.ui.theme.colorSchemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.looker.kenko.R

// Gruvbox — Light & Dark (retro warm)

private val primaryLight = Color(0xFFB57614)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFDEB8)
private val onPrimaryContainerLight = Color(0xFF3D1E00)
private val secondaryLight = Color(0xFF8F3F71)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFD7EF)
private val onSecondaryContainerLight = Color(0xFF3A002A)
private val tertiaryLight = Color(0xFF427B58)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC2FFD6)
private val onTertiaryContainerLight = Color(0xFF00331A)
private val errorLight = Color(0xFF9D0006)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD5)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFFBF1C7)
private val onBackgroundLight = Color(0xFF3C3836)
private val surfaceLight = Color(0xFFFBF1C7)
private val onSurfaceLight = Color(0xFF3C3836)
private val surfaceVariantLight = Color(0xFFEBDBB2)
private val onSurfaceVariantLight = Color(0xFF504945)
private val outlineLight = Color(0xFF7C6F64)
private val outlineVariantLight = Color(0xFFD5C4A1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF3C3836)
private val inverseOnSurfaceLight = Color(0xFFF5EFD8)
private val inversePrimaryLight = Color(0xFFD79921)
private val surfaceDimLight = Color(0xFFDDD2AA)
private val surfaceBrightLight = Color(0xFFFBF1C7)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF7ECC2)
private val surfaceContainerLight = Color(0xFFF1E6BD)
private val surfaceContainerHighLight = Color(0xFFEBE1B8)
private val surfaceContainerHighestLight = Color(0xFFE5DBB2)

private val primaryLightMediumContrast = Color(0xFF935E00)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFFD1902E)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF712355)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFFAA5588)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF255E3E)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF59946E)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF7E0002)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFC02E23)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFBF1C7)
private val onBackgroundLightMediumContrast = Color(0xFF3C3836)
private val surfaceLightMediumContrast = Color(0xFFFBF1C7)
private val onSurfaceLightMediumContrast = Color(0xFF3C3836)
private val surfaceVariantLightMediumContrast = Color(0xFFEBDBB2)
private val onSurfaceVariantLightMediumContrast = Color(0xFF4C4541)
private val outlineLightMediumContrast = Color(0xFF6C615A)
private val outlineVariantLightMediumContrast = Color(0xFF887D75)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF3C3836)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFD8)
private val inversePrimaryLightMediumContrast = Color(0xFFD79921)
private val surfaceDimLightMediumContrast = Color(0xFFDDD2AA)
private val surfaceBrightLightMediumContrast = Color(0xFFFBF1C7)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF7ECC2)
private val surfaceContainerLightMediumContrast = Color(0xFFF1E6BD)
private val surfaceContainerHighLightMediumContrast = Color(0xFFEBE1B8)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFE5DBB2)

private val primaryLightHighContrast = Color(0xFF4B2600)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF935E00)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF460034)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF712355)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF002E13)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF255E3E)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF7E0002)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFBF1C7)
private val onBackgroundLightHighContrast = Color(0xFF3C3836)
private val surfaceLightHighContrast = Color(0xFFFBF1C7)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFEBDBB2)
private val onSurfaceVariantLightHighContrast = Color(0xFF2C2623)
private val outlineLightHighContrast = Color(0xFF4C4541)
private val outlineVariantLightHighContrast = Color(0xFF4C4541)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF3C3836)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFFFE8D1)
private val surfaceDimLightHighContrast = Color(0xFFDDD2AA)
private val surfaceBrightLightHighContrast = Color(0xFFFBF1C7)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF7ECC2)
private val surfaceContainerLightHighContrast = Color(0xFFF1E6BD)
private val surfaceContainerHighLightHighContrast = Color(0xFFEBE1B8)
private val surfaceContainerHighestLightHighContrast = Color(0xFFE5DBB2)

private val primaryDark = Color(0xFFD79921)
private val onPrimaryDark = Color(0xFF422800)
private val primaryContainerDark = Color(0xFF8F5200)
private val onPrimaryContainerDark = Color(0xFFFFDEB8)
private val secondaryDark = Color(0xFFB16286)
private val onSecondaryDark = Color(0xFF45223A)
private val secondaryContainerDark = Color(0xFF6F2E58)
private val onSecondaryContainerDark = Color(0xFFFFD7EF)
private val tertiaryDark = Color(0xFF689D6A)
private val onTertiaryDark = Color(0xFF083A1D)
private val tertiaryContainerDark = Color(0xFF2B5E3D)
private val onTertiaryContainerDark = Color(0xFFC2FFD6)
private val errorDark = Color(0xFFCC241D)
private val onErrorDark = Color(0xFF470003)
private val errorContainerDark = Color(0xFF7E1A16)
private val onErrorContainerDark = Color(0xFFFFDAD5)
private val backgroundDark = Color(0xFF282828)
private val onBackgroundDark = Color(0xFFEBDBB2)
private val surfaceDark = Color(0xFF282828)
private val onSurfaceDark = Color(0xFFEBDBB2)
private val surfaceVariantDark = Color(0xFF3C3836)
private val onSurfaceVariantDark = Color(0xFFD5C4A1)
private val outlineDark = Color(0xFF7C6F64)
private val outlineVariantDark = Color(0xFF3C3836)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEBDBB2)
private val inverseOnSurfaceDark = Color(0xFF3C3836)
private val inversePrimaryDark = Color(0xFFB57614)
private val surfaceDimDark = Color(0xFF1D2021)
private val surfaceBrightDark = Color(0xFF3C3836)
private val surfaceContainerLowestDark = Color(0xFF121414)
private val surfaceContainerLowDark = Color(0xFF282828)
private val surfaceContainerDark = Color(0xFF2C2C2B)
private val surfaceContainerHighDark = Color(0xFF32302F)
private val surfaceContainerHighestDark = Color(0xFF3D3A39)

private val primaryDarkMediumContrast = Color(0xFFF2C065)
private val onPrimaryDarkMediumContrast = Color(0xFF241100)
private val primaryContainerDarkMediumContrast = Color(0xFFB27C1E)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFDF9EBB)
private val onSecondaryDarkMediumContrast = Color(0xFF2B001C)
private val secondaryContainerDarkMediumContrast = Color(0xFF927195)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFA3D5A2)
private val onTertiaryDarkMediumContrast = Color(0xFF00200B)
private val tertiaryContainerDarkMediumContrast = Color(0xFF508458)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFB3A8)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF282828)
private val onBackgroundDarkMediumContrast = Color(0xFFEBDBB2)
private val surfaceDarkMediumContrast = Color(0xFF282828)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFBF4)
private val surfaceVariantDarkMediumContrast = Color(0xFF3C3836)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFDDD0B7)
private val outlineDarkMediumContrast = Color(0xFFB2A690)
private val outlineVariantDarkMediumContrast = Color(0xFF908470)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFEBDBB2)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF32302F)
private val inversePrimaryDarkMediumContrast = Color(0xFF8F5200)
private val surfaceDimDarkMediumContrast = Color(0xFF1D2021)
private val surfaceBrightDarkMediumContrast = Color(0xFF3C3836)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF121414)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF282828)
private val surfaceContainerDarkMediumContrast = Color(0xFF2C2C2B)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF32302F)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3A39)

private val primaryDarkHighContrast = Color(0xFFFFFBF4)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFF2C065)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFFF9F9)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFDF9EBB)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFF1FFF2)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFA3D5A2)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFB3A8)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF282828)
private val onBackgroundDarkHighContrast = Color(0xFFEBDBB2)
private val surfaceDarkHighContrast = Color(0xFF282828)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF3C3836)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFBF4)
private val outlineDarkHighContrast = Color(0xFFDDD0B7)
private val outlineVariantDarkHighContrast = Color(0xFFDDD0B7)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEBDBB2)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF371D00)
private val surfaceDimDarkHighContrast = Color(0xFF1D2021)
private val surfaceBrightDarkHighContrast = Color(0xFF3C3836)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF121414)
private val surfaceContainerLowDarkHighContrast = Color(0xFF282828)
private val surfaceContainerDarkHighContrast = Color(0xFF2C2C2B)
private val surfaceContainerHighDarkHighContrast = Color(0xFF32302F)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF3D3A39)

private val gruvboxLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val gruvboxDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val gruvboxMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val gruvboxHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val gruvboxMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val gruvboxHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val gruvboxColorSchemes = ColorSchemes(
    light = gruvboxLightScheme,
    dark = gruvboxDarkScheme,
    mediumContrastLight = gruvboxMediumContrastLightColorScheme,
    mediumContrastDark = gruvboxMediumContrastDarkColorScheme,
    highContrastLight = gruvboxHighContrastLightColorScheme,
    highContrastDark = gruvboxHighContrastDarkColorScheme,
    nameRes = R.string.label_color_scheme_gruvbox,
)
