/*
 * Copyright (C) 2025 LooKeR & Contributors
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.looker.kenko.ui.theme.colorSchemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.looker.kenko.R

// Tokyo Night — Day (Light) & Storm (Dark)

private val primaryLight = Color(0xFF2E7DE9)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFD6E4FF)
private val onPrimaryContainerLight = Color(0xFF001B5E)
private val secondaryLight = Color(0xFF7847BD)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFF3E5FF)
private val onSecondaryContainerLight = Color(0xFF2D004E)
private val tertiaryLight = Color(0xFF007197)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC4F0FF)
private val onTertiaryContainerLight = Color(0xFF002230)
private val errorLight = Color(0xFFC64343)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFD5D6DB)
private val onBackgroundLight = Color(0xFF343B58)
private val surfaceLight = Color(0xFFD5D6DB)
private val onSurfaceLight = Color(0xFF343B58)
private val surfaceVariantLight = Color(0xFFC1C2C7)
private val onSurfaceVariantLight = Color(0xFF43465A)
private val outlineLight = Color(0xFF73768A)
private val outlineVariantLight = Color(0xFFC1C2C7)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF343B58)
private val inverseOnSurfaceLight = Color(0xFFEDEEF6)
private val inversePrimaryLight = Color(0xFF7AA2F7)
private val surfaceDimLight = Color(0xFFB6B7BC)
private val surfaceBrightLight = Color(0xFFD5D6DB)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFDFE0E5)
private val surfaceContainerLight = Color(0xFFD5D6DB)
private val surfaceContainerHighLight = Color(0xFFCFD0D5)
private val surfaceContainerHighestLight = Color(0xFFCACBD0)

private val primaryLightMediumContrast = Color(0xFF0046B5)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF5A95FF)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF5D2A9E)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF9460D6)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF00536E)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF2D8CB3)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFFA42828)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFE05B5B)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFD5D6DB)
private val onBackgroundLightMediumContrast = Color(0xFF343B58)
private val surfaceLightMediumContrast = Color(0xFFD5D6DB)
private val onSurfaceLightMediumContrast = Color(0xFF343B58)
private val surfaceVariantLightMediumContrast = Color(0xFFC1C2C7)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3F4256)
private val outlineLightMediumContrast = Color(0xFF5F6276)
private val outlineVariantLightMediumContrast = Color(0xFF7B7E92)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF343B58)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFEDEEF6)
private val inversePrimaryLightMediumContrast = Color(0xFF7AA2F7)
private val surfaceDimLightMediumContrast = Color(0xFFB6B7BC)
private val surfaceBrightLightMediumContrast = Color(0xFFD5D6DB)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFDFE0E5)
private val surfaceContainerLightMediumContrast = Color(0xFFD5D6DB)
private val surfaceContainerHighLightMediumContrast = Color(0xFFCFD0D5)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFCACBD0)

private val primaryLightHighContrast = Color(0xFF00215C)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF0046B5)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF380062)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF5D2A9E)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF002B3D)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF00536E)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF4E0002)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFFA42828)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFD5D6DB)
private val onBackgroundLightHighContrast = Color(0xFF343B58)
private val surfaceLightHighContrast = Color(0xFFD5D6DB)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFC1C2C7)
private val onSurfaceVariantLightHighContrast = Color(0xFF202337)
private val outlineLightHighContrast = Color(0xFF3F4256)
private val outlineVariantLightHighContrast = Color(0xFF3F4256)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF343B58)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFDBE6FF)
private val surfaceDimLightHighContrast = Color(0xFFB6B7BC)
private val surfaceBrightLightHighContrast = Color(0xFFD5D6DB)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFDFE0E5)
private val surfaceContainerLightHighContrast = Color(0xFFD5D6DB)
private val surfaceContainerHighLightHighContrast = Color(0xFFCFD0D5)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCACBD0)

private val primaryDark = Color(0xFF7AA2F7)
private val onPrimaryDark = Color(0xFF0F1A3B)
private val primaryContainerDark = Color(0xFF2A3A6B)
private val onPrimaryContainerDark = Color(0xFFD6E4FF)
private val secondaryDark = Color(0xFFBB9AF7)
private val onSecondaryDark = Color(0xFF28144B)
private val secondaryContainerDark = Color(0xFF47357A)
private val onSecondaryContainerDark = Color(0xFFF3E5FF)
private val tertiaryDark = Color(0xFF7DCFFF)
private val onTertiaryDark = Color(0xFF003544)
private val tertiaryContainerDark = Color(0xFF1B5A6E)
private val onTertiaryContainerDark = Color(0xFFC4F0FF)
private val errorDark = Color(0xFFF7768E)
private val onErrorDark = Color(0xFF561A20)
private val errorContainerDark = Color(0xFF73333A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF1A1B26)
private val onBackgroundDark = Color(0xFFC0CAF5)
private val surfaceDark = Color(0xFF1A1B26)
private val onSurfaceDark = Color(0xFFC0CAF5)
private val surfaceVariantDark = Color(0xFF3B4261)
private val onSurfaceVariantDark = Color(0xFF9AA5CE)
private val outlineDark = Color(0xFF565F89)
private val outlineVariantDark = Color(0xFF3B4261)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFC0CAF5)
private val inverseOnSurfaceDark = Color(0xFF343B58)
private val inversePrimaryDark = Color(0xFF2E7DE9)
private val surfaceDimDark = Color(0xFF0F101A)
private val surfaceBrightDark = Color(0xFF2F3140)
private val surfaceContainerLowestDark = Color(0xFF0B0C14)
private val surfaceContainerLowDark = Color(0xFF1A1B26)
private val surfaceContainerDark = Color(0xFF1E1F2A)
private val surfaceContainerHighDark = Color(0xFF282A35)
private val surfaceContainerHighestDark = Color(0xFF333540)

private val primaryDarkMediumContrast = Color(0xFFB2C9FF)
private val onPrimaryDarkMediumContrast = Color(0xFF001135)
private val primaryContainerDarkMediumContrast = Color(0xFF537CC8)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFD9BFFF)
private val onSecondaryDarkMediumContrast = Color(0xFF22003D)
private val secondaryContainerDarkMediumContrast = Color(0xFF8E68CC)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFB0E7FF)
private val onTertiaryDarkMediumContrast = Color(0xFF002634)
private val tertiaryContainerDarkMediumContrast = Color(0xFF4BA8C8)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFB3AE)
private val onErrorDarkMediumContrast = Color(0xFF370001)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF1A1B26)
private val onBackgroundDarkMediumContrast = Color(0xFFC0CAF5)
private val surfaceDarkMediumContrast = Color(0xFF1A1B26)
private val onSurfaceDarkMediumContrast = Color(0xFFFDFBFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF3B4261)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFC0C9ED)
private val outlineDarkMediumContrast = Color(0xFF999FC3)
private val outlineVariantDarkMediumContrast = Color(0xFF797FA2)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFC0CAF5)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A35)
private val inversePrimaryDarkMediumContrast = Color(0xFF2A3A6B)
private val surfaceDimDarkMediumContrast = Color(0xFF0F101A)
private val surfaceBrightDarkMediumContrast = Color(0xFF2F3140)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0B0C14)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1B26)
private val surfaceContainerDarkMediumContrast = Color(0xFF1E1F2A)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF282A35)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF333540)

private val primaryDarkHighContrast = Color(0xFFFDFBFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFB2C9FF)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
private val secondaryDarkHighContrast = Color(0xFFFFF9FD)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFD9BFFF)
private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
private val tertiaryDarkHighContrast = Color(0xFFF4FBFF)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFB0E7FF)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
private val errorDarkHighContrast = Color(0xFFFFF9F9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFB3AE)
private val onErrorContainerDarkHighContrast = Color(0xFF000000)
private val backgroundDarkHighContrast = Color(0xFF1A1B26)
private val onBackgroundDarkHighContrast = Color(0xFFC0CAF5)
private val surfaceDarkHighContrast = Color(0xFF1A1B26)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF3B4261)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFDFBFF)
private val outlineDarkHighContrast = Color(0xFFC0C9ED)
private val outlineVariantDarkHighContrast = Color(0xFFC0C9ED)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFC0CAF5)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF001B53)
private val surfaceDimDarkHighContrast = Color(0xFF0F101A)
private val surfaceBrightDarkHighContrast = Color(0xFF2F3140)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF0B0C14)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1A1B26)
private val surfaceContainerDarkHighContrast = Color(0xFF1E1F2A)
private val surfaceContainerHighDarkHighContrast = Color(0xFF282A35)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF333540)

private val tokyoNightLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val tokyoNightDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val tokyoNightMediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val tokyoNightHighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val tokyoNightMediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val tokyoNightHighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val tokyoNightColorSchemes = ColorSchemes(
    light = tokyoNightLightScheme,
    dark = tokyoNightDarkScheme,
    mediumContrastLight = tokyoNightMediumContrastLightColorScheme,
    mediumContrastDark = tokyoNightMediumContrastDarkColorScheme,
    highContrastLight = tokyoNightHighContrastLightColorScheme,
    highContrastDark = tokyoNightHighContrastDarkColorScheme,
    nameRes = R.string.label_color_scheme_tokyo_night,
)
